### ISSUE TITLE
Execute custom command to stop the app

### ISSUE THREAD

**Issue by SubrataM3** [jlesage/docker-baseimage#5]
Hi,

Is it possible to execute custom command (like sending graceful shutdown command which is normally not happening with my app) when container is shutting down ? 
I can see you already have a finish script, So i am not sure where else to set those commands.

Thanks.

**Comment by jlesage** [comment]
The way to achieve that is to use `startapp.sh` as a wrapper to your application.  So the wrapper will receive the termination signal (instead of your application) and can then kill the application properly.

For example: https://github.com/jlesage/docker-crashplan-pro/blob/master/rootfs/startapp.sh

**Comment by SubrataM3** [comment]
Hi,

Thanks for your fast reply.  I have a small doubt on that script. I see that $PID is passed as a argument to exit_crashplan but it is not used within that function. Also i have checked the [manpage](https://manpages.debian.org/testing/xdotool/xdotool.1.en.html) , can't find any way to pass PID to the `key [options] keystroke` .  Can you clarify this a bit?
Thanks

**Comment by jlesage** [comment]
The pid is not needed.  `xdotool` sends the key to the active window.
